### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/message-format-2.0-rs#3]
Do we want to write a parser to accompany the AST?

We could either write something by hand (I have a lot of experience writing parsers in Rust, and I believe for the initial subset we could have a sub-100 lines of code parser), or we can use a generator like `nom`.

**Comment by echeran** [comment]
I think it would keep our work focused on the core functionality if we leave aside parser concerns to begin with.  Rust syntax is expressive enough to represent maps (associative) and vectors (sequential) fairly well, which lets us represent any structure of data that is appropriate input to a MF API.

I [define AST](https://github.com/unicode-org/message-format-wg/pull/80) (Abstract Syntax Tree) as the tree that pops out when you parse a file according to its syntax.  It's often used in the context of parsing executable code, but not strictly limited to such.  It's [not exactly](https://www.google.com/search?q=abstract+syntax+tree&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjz5a6l-4nqAhWDJTQIHRUZA2MQ_AUoAXoECBEQAw&biw=1281&bih=927) what we need -- perhaps it's a bit lower level.

We can start off by just describing the input data for a message formatter -- maybe you start off with a target locale, a message template (interleaved strings and placeholders), and some specific values to plug into the template?  Something like that might be enough to drive the code, in a "data-driven" way, where the other part of the work is producing the impl functions to make the output behave as we expect.  And later on, we can build serialization upon that as needed.

**Comment by zbraniecki** [comment]
I see. Yeah, that makes sense!

**Comment by zbraniecki** [comment]
I'll close it for now then, and we can later reopen if needed.
